facultymodule/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views


app_name = 'facultymodule'

urlpatterns = [
    path('course/',views.postcourse,name='postcourse'),
    path('add_coursedetails/',views.add_coursedetails,name='add_coursedetails'),
    path('view/',views.viewcoursedetails,name='viewcoursedetails'),
    path('edit/<int:cid>/', views.editcoursedetails, name='editcoursedetails'),
    path('delete/<int:cid>/', views.deletecoursedetails, name='deletecoursedetails'),
    path('courseapplicationlist/',views.courseapplicationlist,name='courseapplicationlist')

]

scm/urls.py
from django.contrib import admin

from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static

from project import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('project.urls')),
    path('studentmodule/',include('studentmodule.urls')),
    path('facultymodule/',include('facultymodule.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_URL)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

studentmodule/urls.py
from django.contrib import admin
from django.urls import path,include
from .import views


app_name='studentmodule'

urlpatterns = [
   path('viewcourse/',views.viewcourse,name='viewcourse'),
   path('coursedetails',views.coursedetails,name='coursedetails'),
   path('submit_form/',views.submit_form,name='submit_form'),
   path('addstudentprofile/',views.addstudentprofile,name='addstudentprofile'),
   path('applycourse/<int:cid>/', views.applycourse,name='applycourse'),
]

templates/Navbar/facultynavbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</head>
<body>
<nav class="navbar navbar-expand-lg" style="background-color:#9195F6">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'projecthomepage' %}">Student Course Management</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'projecthomepage' %}">Home</a>
        </li>
        <!--<li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>-->
          <li class="nav-item">
          <a class="nav-link" href="{% url 'facultymodule:postcourse' %}">Post Course</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'facultymodule:viewcoursedetails'%}">View Courses</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'facultymodule:courseapplicationlist'%}">View Course Applications</a>
        </li>
       <!-- <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>-->

      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>

      <!---<ul class = "navbar-nav ms-auto">
     <li class="nav-item">
          <a class="nav-link" href="{% url 'studenthomepage' %}">Student</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'facultyhomepage' %}">Faculty</a>
        </li>
        </ul>-->

       <ul class="navbar-nav ms-auto">
        <li>
          {% if user.is_authenticated %}
          <li class="nav-item">
        <span class="nav-link">Welcome ,{{user.username}}</span>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}">Logout</a>
        </li>
        {% else %}
         <li class="nav-item">
          <a class="nav-link" href="{% url 'register' %}">Register</a>
        </li>
         <li class="nav-item">
          <a class="nav-link" href="{% url 'login' %}">Login</a>
        </li>
        {% endif %}

      </ul>
    </div>
  </div>
</nav>
{% block body %}

{% endblock%}
<footer id="sticky-footer" class="flex-shrink=0 py-2">
  <div class="container text-center">
    <small>Copyright Sanjana.N - KL University.All rights reserved</small>
  </div>
</footer>
<style>
  #sticky-footer {
  position:fixed;
  bottom:0;
  left:0;
  right:0;
  background-color:#1F2544;
  color:white;
  padding:10px;
  font-weight: bold;
  }
</style>
</body>
</html>

templates/Navbar/projectnavbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</head>
<body>
<nav class="navbar navbar-expand-lg" style="background-color:#E3E1D9">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'projecthomepage' %}">Student Course Management</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'projecthomepage' %}">Home</a>
        </li>
        <!--<li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>-->

      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
     <!-- <ul class = "navbar-nav ms-auto">
      <li class="nav-item">
          <a class="nav-link" href="{% url 'studenthomepage' %}">Student</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'facultyhomepage' %}">Faculty</a>
        </li>
        </ul>-->
      <ul class="navbar-nav ms-auto">
        <li>
          {% if user.is_authenticated %}
          <li class="nav-item">
        <span class="nav-link">Welcome ,{{user.username}}</span>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}">Logout</a>
        </li>
        {% else %}
         <li class="nav-item">
          <a class="nav-link" href="{% url 'register' %}">Register</a>
        </li>
         <li class="nav-item">
          <a class="nav-link" href="{% url 'login' %}">Login</a>
        </li>
        {% endif %}

      </ul>
    </div>
  </div>
</nav>
{% block body %}

{% endblock%}
<footer id="sticky-footer" class="flex-shrink=0 py-2">
  <div class="container text-center">
    <small>Copyright Sanjana.N - KL University.All rights reserved</small>
  </div>
</footer>
<style>
  #sticky-footer {
  position:fixed;
  bottom:0;
  left:0;
  right:0;
  background-color:#1F2544;
  color:white;
  padding:10px;
  font-weight: bold;
  }
</style>
</body>
</html>

templates/Navbar/studentnavbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</head>
<body>
<nav class="navbar navbar-expand-lg" style="background-color:#FF004D">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'projecthomepage' %}">Student Course Management</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'projecthomepage' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'studentmodule:addstudentprofile' %}">Profile</a>
        </li>
         <li class="nav-item">
          <a class="nav-link" href="{% url 'studentmodule:coursedetails' %}">View Course</a>
        </li>
        <!--<li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>-->

      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
      <!--<ul class = "navbar-nav ms-auto">
      <li class="nav-item">
          <a class="nav-link" href="{% url 'studenthomepage' %}">Student</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'facultyhomepage' %}">Faculty</a>
        </li>
        </ul>-->
       <ul class="navbar-nav ms-auto">
        <li>
          {% if user.is_authenticated %}
          <li class="nav-item">
        <span class="nav-link">Welcome ,{{user.username}}</span>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}">Logout</a>
        </li>
        {% else %}
         <li class="nav-item">
          <a class="nav-link" href="{% url 'register' %}">Register</a>
        </li>
         <li class="nav-item">
          <a class="nav-link" href="{% url 'login' %}">Login</a>
        </li>
        {% endif %}

      </ul>
    </div>
  </div>
</nav>
{% block body %}

{% endblock%}
<footer id="sticky-footer" class="flex-shrink=0 py-2">
  <div class="container text-center">
    <small>Copyright Sanjana.N - KL University.All rights reserved</small>
  </div>
</footer>
<style>
  #sticky-footer {
  position:fixed;
  bottom:0;
  left:0;
  right:0;
  background-color:#1F2544;
  color:white;
  padding:10px;
  font-weight: bold;
  }
</style>
</body>
</html>