scm/urls.py
from django.contrib import admin

from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static

from project import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('project.urls')),
    path('studentmodule/',include('studentmodule.urls')),
    path('facultymodule/',include('facultymodule.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_URL)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

studentmodule/urls.py
from django.contrib import admin
from django.urls import path,include
from .import views


app_name='studentmodule'

urlpatterns = [
   path('viewcourse/',views.viewcourse,name='viewcourse'),
   path('coursedetails',views.coursedetails,name='coursedetails'),
   path('submit_form/',views.submit_form,name='submit_form'),
   path('addstudentprofile/',views.addstudentprofile,name='addstudentprofile'),
   path('applycourse/<int:cid>/', views.applycourse,name='applycourse'),
]

studentmodule/models.py
from django.db import models

# Create your models here.
class Applicant(models.Model):
    firstname = models.CharField(max_length=100)
    lastname = models.CharField(max_length=100)
    phonenumber = models.CharField(max_length=10)
    address = models.TextField()
    tenthmarks = models.CharField(max_length=10)
    twelfthmarks = models.CharField(max_length=10)

    def __str__(self):
        return f"{self.firstname} {self.lastname}"

from facultymodule.models import courseDetails
class courseapplication(models.Model):
    coursedetails = models.ForeignKey(courseDetails, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    email = models.EmailField()
    certificate = models.FileField(upload_to='certificate/')

    def __str__(self):
        return f"{self.name} - {self.coursedetails}"  # Adjust this line as needed

studentmodule/forms.py
from django import forms

from .models import *


class courseapplicationform(forms.ModelForm):
    class Meta:
      model=courseapplication
      fields= ['name','email','certificate']
    def __init__(self, *args, **kwargs):
        super(courseapplicationform,self).__init__(*args, **kwargs)

studentmodule/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from .models import *
def viewcourse(request):
    return render(request,'studentmodule/viewcourse.html')

from facultymodule.models import courseDetails
def coursedetails(request):
    coursedetailslist = courseDetails.objects.all()
    return render(request,'studentmodule/viewcourse.html',{'coursedetailslist': coursedetailslist})
# Create your views here.

def addstudentprofile(request):
    return render(request,'studentmodule/profile.html')

def submit_form(request):
    if request.method == 'POST':
        firstname = request.POST.get('firstname', '')
        lastname = request.POST.get('lastname', '')
        phonenumber = request.POST.get('phonenumber', '')
        address = request.POST.get('address', '')
        tenthmarks = request.POST.get('tenthmarks', '')
        twelfthmarks = request.POST.get('twelfthmarks', '')

        # Check if all required fields are present
        if firstname and lastname and phonenumber and address and tenthmarks and twelfthmarks:
            applicant = Applicant(firstname=firstname,
                                  lastname=lastname,
                                  phonenumber=phonenumber,
                                  address=address,
                                  tenthmarks=tenthmarks,
                                  twelfthmarks=twelfthmarks)
            applicant.save()
            return render(request, 'studenthomepage.html')

    return render(request, 'studenthomepage.html')

from django.shortcuts import render,redirect
from .forms import *
from django.core.mail import send_mail
def applycourse(request,cid):
    coursedetails=get_object_or_404(courseDetails,id=cid)
    if request.method=='POST':
        form=courseapplicationform(request.POST, request.FILES)
        if form.is_valid():
            courseapplication = form.save(commit=False)
            courseapplication.coursedetails = coursedetails
            courseapplication.save()

            subject = 'Course Details Received'
            message = 'Thank You for registering. Your application is received and will be sent to next process'
            from_email='sanjana031103@gmail.com'
            recipient_list = [courseapplication.email]
            send_mail(subject,message,from_email,recipient_list)
        return redirect('studentmodule:coursedetails')
    else:
        form=courseapplicationform()
    return render(request,'studentmodule/applycourse.html',{'coursedetails':coursedetails, 'form': form})

templates/studentmodule/applycourse.html
{% extends 'Navbar/studentnavbar.html' %}
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Apply to Job</title>
</head>
<body>
{% block body %}
<div class="container mt-5">
    <h2>Register to Course</h2>

    <div class="row">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">{{ coursedetails.courseid }}</h5>
                    <p class="card-text">
                        <strong>CourseID:</strong> {{ coursedetails.coursename }}<br>
                        <strong>OfferedBy:</strong> {{ coursedetails.offeredby }}<br>
                        <strong>OfferingYear:</strong> {{ coursedetails.offeringyear }}<br>
                        <strong>Credits:</strong> {{ coursedetails.credits }}<br>
                    </p>
                </div>
            </div>
        </div>

        <div class="col-md-6">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}

                <!-- Hidden field to store the job_id -->
                <input type="hidden" name="cid" value="{{ coursedetails.id }}">

                <div class="form-group">
                    <label for="name">Your Name:</label>
                    <input type="text" class="form-control" name="name" required>
                </div>

                <div class="form-group">
                    <label for="email">Your Email:</label>
                    <input type="email" class="form-control" name="email" required>
                </div>

                <div class="form-group">
                    <label for="certificate">Upload 12th Marks-memo:</label>
                    <input type="file" class="form-control-file" name="certificate" accept=".pdf, .doc, .docx" required>
                </div>

                <!--<div class="form-group">
                    <label for="cover_letter">Cover Letter:</label>
                    <textarea class="form-control" name="cover_letter" required></textarea>
                </div>-->

                <button type="submit" class="btn btn-success">Register Course</button>
             </form>
        </div>
    </div>
</div>
{% endblock %}
</body>
</html>

templates/studentmodule/profile.html
{% extends 'Navbar/studentnavbar.html' %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Student Profile</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
{% block body %}
<div class="container mt-5">
    <h1>Student Profile</h1>
    <div>
        <h2>Course Application Form</h2>
        <form method="post" action="{% url 'studentmodule:submit_form' %}">
            {% csrf_token %}
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="firstname">First Name</label>
                    <input type="text" class="form-control" name='firstname' id="firstname" placeholder="Enter your first name">
                </div>
                <div class="form-group col-md-6">
                    <label for="lastname">Last Name</label>
                    <input type="text" class="form-control" name='lastname' id="lastname" placeholder="Enter your last name">
                </div>
            </div>

            <div class="form-group">
                <label for="phonenumber">Phone Number</label>
                <input type="tel" class="form-control" name='phonenumber' id="phonenumber" placeholder="Enter your phone number">
            </div>

            <div class="form-group">
                <label for="address">Address</label>
                <input type="text" class="form-control" name='address' id="address" placeholder="Enter your address">
            </div>

            <div class="form-row">
                <div class="form-group col-md-4">
                    <label for="tenthmarks">10th Marks</label>
                    <input type="text" class="form-control" name='tenthmarks' id="tenthmarks" placeholder="Enter your 10th marks">
                </div>
                <div class="form-group col-md-4">
                    <label for="twelfthmarks">12th Marks</label>
                    <input type="text" class="form-control" name='twelfthmarks' id="twelfthmarks" placeholder="Enter your 12th marks">
                </div>
            </div>

            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>

{% endblock %}
</body>
</html>

templates/studentmodule/viewcourse.html
{% extends 'Navbar/studentnavbar.html' %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block body %}
<div class="container mt-5">
    <h2>Course Details</h2>

    <div class="row">
        {% for coursedetails in coursedetailslist %}
        <div class="col-md-4 mb-4">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">{{ coursedetails.courseid }}</h5>
                    <p class="card-text">
                        <strong>Course_Name:</strong> {{ coursedetails.coursename }}<br>
                        <strong>Offered_By:</strong> {{ coursedetails.offeredby }}<br>
                        <strong>Offering_Year:</strong> {{ coursedetails.offeringyear }}<br>
                        <strong>Credits:</strong> {{ coursedetails.credits }}<br>
                    </p>
                    <a href="{% url 'studentmodule:applycourse' coursedetails.id%}" class="btn btn-success">Register Course</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}
</body>
</html>